# Generated by Django 4.2.6 on 2023-10-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(unique=True)),
                ('emails', models.TextField()),
                ('phones', models.TextField()),
            ],
        ),
    ]
