# Generated by Django 4.2.6 on 2023-11-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='file',
            field=models.FileField(default='default_file.txt', upload_to='uploads/'),
        ),
    ]
