# Generated by Django 4.2.6 on 2023-11-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_websiteinfo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='default_file.txt', upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='websiteinfo',
            name='file',
        ),
    ]
