# Generated by Django 4.2.6 on 2023-11-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_fileupload_remove_websiteinfo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
