# Generated by Django 5.1 on 2024-08-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name': 'Uploaded file', 'verbose_name_plural': 'Uploaded files'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='websiteinfo',
            options={'verbose_name': 'Site information', 'verbose_name_plural': 'Information about sites'},
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='fileupload',
            table='file_uploads',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
        migrations.AlterModelTable(
            name='websiteinfo',
            table='website_infos',
        ),
    ]
