# Generated by Django 5.1.1 on 2024-09-13 14:20

import application.types
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_rename_file_fileupload_filename_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[(application.types.StatusType['NOT_STARTED'], 'not_started'), (application.types.StatusType['PENDING'], 'pending'), (application.types.StatusType['PARSING'], 'parsing'), (application.types.StatusType['SAVING'], 'saving'), (application.types.StatusType['DONE'], 'done'), (application.types.StatusType['ERROR'], 'error')], default=application.types.StatusType['NOT_STARTED'], max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
